### ISSUE TITLE
Wrong jedi version 

### ISSUE THREAD

**Issue by martinRenou** [conda-forge/xeus-python-feedstock#42]
We need to bump the jedi version to the the latest, and increase the build number

**Comment by JohanMabille** [comment]
Don't we need https://github.com/QuantStack/xeus-python/pull/151 to be merged before bumping the jedi version?

**Comment by martinRenou** [comment]
Oh sorry, I thought you merged it. Nevermind :smile:

**Comment by JohanMabille** [comment]
The problem with the tests that never end is still there (I've restarted the build and got the same result).

**Comment by martinRenou** [comment]
I'll look into it. Thanks :)
