### ISSUE TITLE
Mark build 0 of `xeus-python-0.6.7` as broken on windows.

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/xeus-python-feedstock#51]
Could someone with the appropriate priviledges mark a package as broken?\

```
win-64/xeus-python-0.6.7-py38h1ad3211_0.tar.bz2
win-64/xeus-python-0.6.7-py37h1ad3211_0.tar.bz2
win-64/xeus-python-0.6.7-py36h1ad3211_0.tar.bz2
```

(i.e. windows builds of xeus-python 0.6.7 with build number 0). We missed a build parameter.

**Comment by SylvainCorlay** [comment]
cc @conda-forge/core

**Comment by SylvainCorlay** [comment]
Closeing. @ocefpaf is just too fast :)

**Comment by ocefpaf** [comment]
Done. Can you please check if I got it right?

**Comment by SylvainCorlay** [comment]
Yes! I think so.
