### ISSUE TITLE
Loosen Jedi Version Requirement

### ISSUE THREAD

**Issue by alanhdu** [conda-forge/xeus-python-feedstock#77]
The current recipe pins the jedi requirement to 0.15.1:

https://github.com/conda-forge/xeus-python-feedstock/blob/eef337ab6056c9c5eeec888edfa288fbab83732d/recipe/meta.yaml#L36

Is there any reason why we don't allow jedi 0.16 or jedi 0.17? From browsing the original repo (https://github.com/jupyter-xeus/xeus-python/blob/master/environment.yml), it looks like the upstream repo `xeus-python` doesn't pin a specific version of jedi, which indicates that it probably works fine against `jedi 0.17` (and FWIW, I have noticed no problems I forcibly `pip` install `jedi=0.17.2` in my environment).

**Comment by SylvainCorlay** [comment]
> Is there any reason why we don't allow jedi 0.16 or jedi 0.17? From browsing the original repo (https://github.com/jupyter-xeus/xeus-python/blob/master/environment.yml), it looks like the upstream repo xeus-python doesn't pin a specific version of jedi, which indicates that it probably works fine against jedi 0.17 (and FWIW, I have noticed no problems I forcibly pip install jedi=0.17.2 in my environment).


This is because 0.16 and 0.17 were not released, and as a good practice, we prevent the next semver-backward incompatible release. Will unpin.

**Comment by JohanMabille** [comment]
This changed has been integrated.
